/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:64f2dcb9-1b08-404b-84df-3527023b88a7",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_DTiFND4kD",
    "aws_user_pools_web_client_id": "55c3i5u9umhpell8afqrft3c2e",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "apib970b207",
            "endpoint": "https://qadpz5atz4.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
